apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-agent
  namespace: chaoslab
spec:
  replicas: 5
  selector:
    matchLabels:
      app: chaos-agent
  template:
    metadata:
      labels:
        app: chaos-agent
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: chaos-agent
        image: chaos-agent:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "2"
            memory: "512Mi"
        env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://otel-collector.observability.svc.cluster.local:4318"
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: "true"
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "SYS_ADMIN"]
