name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Run Go Tests
        run: |
          cd controller && go test -v ./...
          cd ../agent && go test -v ./...

      - name: Build Docker Images
        run: |
          docker build -f infrastructure/Dockerfile.controller -t ${{ secrets.DOCKER_USERNAME }}/chaos-controller:latest .
          docker build -f infrastructure/Dockerfile.agent -t ${{ secrets.DOCKER_USERNAME }}/chaos-agent:latest .
          docker build -f dashboard/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/chaos-dashboard:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/chaos-controller:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/chaos-agent:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/chaos-dashboard:latest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.21.0"

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f infrastructure/k8s/controller-deployment.yaml -n chaoslab
          kubectl apply -f infrastructure/k8s/agent-deployment.yaml -n chaoslab
          kubectl apply -f infrastructure/k8s/dashboard-deployment.yaml -n chaoslab
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
